[FileDialog]
history=file:///home/aspen/Downloads/The Worst Person in the World [2021 - Norway] comedy, file:///home/aspen/Downloads/The Worst Person in the World (2021) Criterion (1080p BluRay x265 HEVC 10bit AAC 5.1 Norwegian Silence), file:///home/aspen/Downloads/Before.Sunrise.1995.1080p.BluRay.x264-DEPTH[rarbg]
lastVisited=file:///home/aspen/Downloads/Before.Sunrise.1995.1080p.BluRay.x264-DEPTH[rarbg]
qtVersion=5.15.18
shortcuts=file:, file:///home/aspen
sidebarWidth=91
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x2\x4\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\x1\x14\0\0\0\x1\0\0\0\0\0\0\0>\0\0\0\x1\0\0\0\0\0\0\0\x42\0\0\0\x1\0\0\0\0\0\0\0p\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff)
viewMode=Detail
